SET GLOBAL log_bin_trust_function_creators = 1;
-- DETERMINISTIC: 언제나 결과가 100% 똑같은 함수 (수학 연산 등)
-- READS SQL DATA: 데이터를 읽거나, NOW()·RAND()를 쓰는 함수 (가장 흔함)
-- MODIFIES SQL DATA: 데이터를 변경(INSERT/UPDATE)하는 함수
-- NO SQL: SQL 문을 아예 안 쓰는 순수 로직 함수

DELIMITER $$

-- 연봉을 구하는 함수
CREATE FUNCTION FN_GET_ANNUAL_SALARY(P_SALARY INT, P_BONUS DECIMAL(4,2))
RETURNS INT
-- 동일한 입력값에 대해 항상 동일한 결과를 반환하는 함수
DETERMINISTIC
BEGIN 
	RETURN (P_SALARY + P_SALARY* IFNULL(P_BONUS,0)) * 12;
END $$

DELIMITER ;

-- 사용자 정의 함수 호출
SELECT FN_GET_ANNUAL_SALARY(2000000, 0.3);
-- 사용자 정의 함수 호출
SELECT  EMP_NAME, SALARY, BONUS, FN_GET_ANNUAL_SALARY(SALARY, BONUS) 연봉
FROM 	EMP;



DESC EMP;
-- 나이를 반환하는 함수
DELIMITER $$
-- 연봉을 구하는 함수 주민등록번호를 매개변수로 받아서 나이를 반환
CREATE FUNCTION GET_AGE(P_EMP_NO char(14))
RETURNS INT
-- NOW()함수를 이용하면 함수의 실행결과가 항상 같지 않다
-- READS SQL DATA
BEGIN 
	DECLARE V_AGE INT;
    SET V_AGE = TIMESTAMPDIFF(YEAR, STR_TO_DATE( CASE WHEN SUBSTRING(P_EMP_NO, 8, 1) IN ('1', '2') THEN CONCAT('19', SUBSTRING(P_EMP_NO, 1, 6))
				WHEN SUBSTRING(P_EMP_NO, 8, 1) IN ('3', '4') THEN CONCAT('20', SUBSTRING(P_EMP_NO, 1, 6))
				END, '%Y%m%d'), NOW());
	RETURN V_AGE;
END $$

DELIMITER ;


DROP FUNCTION GET_AGE;

SELECT GET_AGE(EMP_NO) 나이
FROM EMP;


SHOW FUNCTION STATUS WHERE Name = 'GET_AGE';

-- 환경변수 설정
SET GLOBAL log_bin_trust_function_creators = 1;

DELIMITER $$
-- 연봉을 구하는 함수 주민등록번호를 매개변수로 받아서 나이를 반환
CREATE FUNCTION GET_AGE(P_EMP_NO char(14))
RETURNS INT
BEGIN 
	DECLARE V_AGE INT;
    SET V_AGE = TIMESTAMPDIFF(YEAR, STR_TO_DATE( CASE WHEN SUBSTRING(P_EMP_NO, 8, 1) IN ('1', '2') THEN CONCAT('19', SUBSTRING(P_EMP_NO, 1, 6))
				WHEN SUBSTRING(P_EMP_NO, 8, 1) IN ('3', '4') THEN CONCAT('20', SUBSTRING(P_EMP_NO, 1, 6))
				END, '%Y%m%d'), NOW());
	RETURN V_AGE;
END $$

DELIMITER ;



-- --------------
-- 프로시저 (Stored Procedure)
-- 여러개의 DML문장을 처리
-- --------------
-- 부서코드와 급여인상률을 파라메터로 전달 받아서 
-- 부서의 사원의 급여를 인상하는 프로시져
DELIMITER $$
CREATE PROCEDURE RAISE_SALARY(IN P_DEPT_ID CHAR(2), IN P_RATE DECIMAL(3,2), OUT P_AVG_SALARY INT)
BEGIN
	
	UPDATE EMP
    SET SALARY = SALARY * (1 + P_RATE)
	WHERE DEPT_ID = P_DEPT_ID;
    
    -- SELECT문의 조회 결과를 변수에 담을수도 있다!
    -- 단일행만 가능!!
    
    SELECT 	AVG(SALARY) INTO P_AVG_SALARY
    FROM 	emp
    WHERE  	DEPT_ID = P_DEPT_ID;
    COMMIT;
END $$
DELIMITER ;

DROP PROCEDURE RAISE_SALARY;
-- 수정,삭제시 인덱스가 사용된 컬럼을 사용하지 않으면 오류를 발생
SET SESSION sql_safe_updates = 0;

-- OUT파라메터는 값을 반환 
-- 사용자변수를 넣어주면 실행 결과를 변수에 담아줌
CALL RAISE_SALARY('D1', 0.1, @AVG_SAL);

-- D1 부서의 평균 급여
SELECT @AVG_SAL;

SELECT SALARY FROM EMP WHERE DEPT_ID = 'D1';


DELIMITER $$

CREATE PROCEDURE FLAG_LOW_SALARY()
BEGIN
    DECLARE V_DONE INT DEFAULT 0;
    DECLARE V_EMP_ID VARCHAR(3);
    DECLARE V_SALARY INT;

    DECLARE CUR CURSOR FOR
        SELECT EMP_ID, SALARY FROM EMP_COPY;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET V_DONE = 1;

    OPEN CUR;

    READ_LOOP: LOOP
        FETCH CUR INTO V_EMP_ID, V_SALARY;
        IF V_DONE = 1 THEN
            LEAVE READ_LOOP;
        END IF;

        IF V_SALARY < 2000000 THEN
            INSERT INTO SALARY_LOG (EMP_ID, OLD_SALARY, NEW_SALARY)
            VALUES (V_EMP_ID, V_SALARY, V_SALARY);
        END IF;
    END LOOP;

    CLOSE CUR;
END $$

DELIMITER ;

CALL FLAG_LOW_SALARY();

SELECT EMP_ID, OLD_SALARY FROM SALARY_LOG ORDER BY EMP_ID;


DROP TABLE IF EXISTS EMP_COPY;
CREATE TABLE EMP_COPY AS SELECT * FROM EMP;

DROP TABLE IF EXISTS SALARY_LOG;
CREATE TABLE SALARY_LOG (
    LOG_ID     INT AUTO_INCREMENT PRIMARY KEY,
    EMP_ID     VARCHAR(3),
    OLD_SALARY INT,
    NEW_SALARY INT,
    CHANGED_AT DATETIME DEFAULT NOW()
);

CREATE TEMPORARY TABLE TMP_GUGU (DAN INT, I INT, RESULT INT);
SELECT * FROM TMP_GUGU;
DELIMITER $$
CREATE PROCEDURE GUGUDAN()
BEGIN
	DECLARE DAN INT DEFAULT 2;
    
    DAN_LOOP : LOOP
		IF DAN > 9 THEN 
			LEAVE DAN_LOOP; 
        END IF;
        
        INSERT INTO TMP_GUGU VALUES(DAN, 0, 0);
        SET DAN = DAN + 1;
    END LOOP;
	
END $$
DELIMITER ;

CALL GUGUDAN();
SELECT * FROM TMP_GUGU;


DROP TABLE IF EXISTS EMP_COPY;
CREATE TABLE EMP_COPY AS SELECT * FROM EMP;

DROP TABLE IF EXISTS SALARY_LOG;
CREATE TABLE SALARY_LOG (
    LOG_ID     INT AUTO_INCREMENT PRIMARY KEY,
    EMP_ID     VARCHAR(3),
    OLD_SALARY INT,
    NEW_SALARY INT,
    CHANGED_AT DATETIME DEFAULT NOW()
);
-- 여러행에 대한 처리 - CURSON
DELIMITER $$

CREATE PROCEDURE FLAG_LOW_SALARY()
BEGIN
	-- 변수 선언
	DECLARE V_DONE INT DEFAULT 0; -- 반복문 탈출 조건
    DECLARE V_EMP_ID VARCHAR(3);
    DECLARE V_SALARY INT;
    
    -- 커서 선언
    DECLARE CUR CURSOR FOR	
		SELECT EMP_ID, SALARY FROM EMP;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET V_DONE = 1; -- 반복문 탈출 조건
    
    -- 쿼리 실행 FETCH 준비
    OPEN CUR;
    READ_LOOP : LOOP
		FETCH CUR INTO V_EMP_ID, V_SALARY;
        IF V_DONE = 1 THEN
			LEAVE READ_LOOP;
        END IF;
        
        IF V_SALARY < 2000000 THEN
			-- 급여 이력 테이블
			INSERT INTO SALARY_LOG VALUES (NULL, V_EMP_ID, V_SALARY, V_SALARY, NULL);
		END IF;
    END LOOP;
	CLOSE CUR;
    
END $$
DELIMITER ;
CALL FLAG_LOW_SALARY();
SELECT * FROM SALARY_LOG;
DROP PROCEDURE FLAG_LOW_SALARY;

