# 1_인덱스.md 본문 실습 진행 스크립트 (Day 15)

# 2. 실습용 대용량 테이블 준비
SET SESSION cte_max_recursion_depth = 5000;

DROP TABLE IF EXISTS BIG_EMP;

CREATE TABLE BIG_EMP AS
WITH RECURSIVE SEQ AS (
    SELECT 1 AS N
    UNION ALL
    SELECT N + 1 FROM SEQ WHERE N < 3000
)
SELECT ROW_NUMBER() OVER (ORDER BY S.N, E.EMP_ID) AS ID,
       E.EMP_NAME, E.DEPT_ID, E.JOB_CODE, E.SALARY, E.HIRE_DATE
FROM SEQ S
CROSS JOIN EMP E;

ALTER TABLE BIG_EMP ADD PRIMARY KEY (ID);

SELECT COUNT(*) FROM BIG_EMP;
SELECT COUNT(*) FROM BIG_EMP WHERE EMP_NAME = '곽상혁';

# 3. EXPLAIN으로 실행계획 보기 (인덱스 생성 전)
SELECT @@explain_format;
EXPLAIN FORMAT=TRADITIONAL SELECT * FROM BIG_EMP WHERE EMP_NAME = '곽상혁';
EXPLAIN FORMAT=TREE SELECT * FROM BIG_EMP WHERE EMP_NAME = '곽상혁';
EXPLAIN ANALYZE SELECT * FROM BIG_EMP WHERE EMP_NAME = '곽상혁';

# 4. CREATE INDEX로 인덱스 생성
CREATE INDEX IDX_BIGEMP_NAME ON BIG_EMP (EMP_NAME);

SHOW INDEX FROM BIG_EMP;

EXPLAIN SELECT * FROM BIG_EMP WHERE EMP_NAME = '곽상혁';
EXPLAIN FORMAT=TREE SELECT * FROM BIG_EMP WHERE EMP_NAME = '곽상혁';

# 5. 복합 인덱스
CREATE INDEX IDX_BIGEMP_DEPT_SALARY ON BIG_EMP (DEPT_ID, SALARY);

EXPLAIN SELECT * FROM BIG_EMP WHERE DEPT_ID = 'D9' AND SALARY >= 5000000;
EXPLAIN SELECT * FROM BIG_EMP WHERE SALARY >= 5000000;

# 6.1 WHERE절 컬럼에 함수를 씌운 경우
CREATE INDEX IDX_BIGEMP_HIRE ON BIG_EMP (HIRE_DATE);

EXPLAIN SELECT * FROM BIG_EMP WHERE YEAR(HIRE_DATE) = 2013;
EXPLAIN FORMAT=TREE SELECT * FROM BIG_EMP WHERE YEAR(HIRE_DATE) = 2013;
EXPLAIN SELECT * FROM BIG_EMP WHERE HIRE_DATE BETWEEN '2013-01-01' AND '2013-12-31';
EXPLAIN FORMAT=TREE SELECT * FROM BIG_EMP WHERE HIRE_DATE BETWEEN '2013-01-01' AND '2013-12-31';

# 6.2 LIKE 앞부분의 와일드카드
EXPLAIN SELECT * FROM BIG_EMP WHERE EMP_NAME LIKE '%상혁';
EXPLAIN SELECT * FROM BIG_EMP WHERE EMP_NAME LIKE '곽%';

# 6.3 타입 불일치(암묵적 형변환) - 원본 EMP로 확인
EXPLAIN SELECT * FROM EMP WHERE EMP_ID = 200;
EXPLAIN SELECT * FROM EMP WHERE EMP_ID = '200';

# 7. DROP INDEX / 정리
DROP INDEX IDX_BIGEMP_NAME ON BIG_EMP;
DROP INDEX IDX_BIGEMP_DEPT_SALARY ON BIG_EMP;
DROP INDEX IDX_BIGEMP_HIRE ON BIG_EMP;

DROP TABLE BIG_EMP;
