# 1_PROCEDURE_TRIGGER.md 본문 실습 진행 스크립트 (Day 17)

# 0. 실습 준비 - 사본 테이블 + 로그 테이블
DROP TABLE IF EXISTS EMP_COPY;
CREATE TABLE EMP_COPY AS SELECT * FROM EMP;

DROP TABLE IF EXISTS SALARY_LOG;
CREATE TABLE SALARY_LOG (
    LOG_ID     INT AUTO_INCREMENT PRIMARY KEY,
    EMP_ID     VARCHAR(3),
    OLD_SALARY INT,
    NEW_SALARY INT,
    CHANGED_AT DATETIME DEFAULT NOW()
);

# 1. PROCEDURE 기본 - IN 파라미터
DELIMITER $$

CREATE PROCEDURE RAISE_SALARY(IN P_DEPT_ID CHAR(2), IN P_RATE DECIMAL(3,2))
BEGIN
    UPDATE EMP_COPY
    SET SALARY = SALARY * (1 + P_RATE)
    WHERE DEPT_ID = P_DEPT_ID;
END $$

DELIMITER ;

CALL RAISE_SALARY('D8', 0.10);

SELECT EMP_ID, EMP_NAME, SALARY FROM EMP_COPY WHERE DEPT_ID = 'D8' ORDER BY EMP_ID;

# 2. OUT 파라미터 - 결과값 반환
DELIMITER $$

CREATE PROCEDURE GET_DEPT_AVG_SALARY(IN P_DEPT_ID CHAR(2), OUT P_AVG_SALARY INT)
BEGIN
    SELECT ROUND(AVG(SALARY)) INTO P_AVG_SALARY
    FROM EMP_COPY
    WHERE DEPT_ID = P_DEPT_ID;
END $$

DELIMITER ;

CALL GET_DEPT_AVG_SALARY('D9', @avg_sal);
SELECT @avg_sal;

# 3. IF 제어문
DELIMITER $$

CREATE PROCEDURE CLASSIFY_SALARY(IN P_EMP_ID VARCHAR(3), OUT P_GRADE VARCHAR(10))
BEGIN
    DECLARE V_SALARY INT;

    SELECT SALARY INTO V_SALARY FROM EMP_COPY WHERE EMP_ID = P_EMP_ID;

    IF V_SALARY >= 5000000 THEN
        SET P_GRADE = '고액';
    ELSEIF V_SALARY >= 2500000 THEN
        SET P_GRADE = '중액';
    ELSE
        SET P_GRADE = '소액';
    END IF;
END $$

DELIMITER ;

CALL CLASSIFY_SALARY('200', @grade);
SELECT @grade;

# 4. WHILE / 커서(CURSOR)
DROP TABLE IF EXISTS EMP_COPY;
CREATE TABLE EMP_COPY AS SELECT * FROM EMP;

DELIMITER $$

CREATE PROCEDURE FLAG_LOW_SALARY()
BEGIN
    DECLARE V_DONE INT DEFAULT 0;
    DECLARE V_EMP_ID VARCHAR(3);
    DECLARE V_SALARY INT;

    DECLARE CUR CURSOR FOR
        SELECT EMP_ID, SALARY FROM EMP_COPY;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET V_DONE = 1;

    OPEN CUR;

    READ_LOOP: LOOP
        FETCH CUR INTO V_EMP_ID, V_SALARY;
        IF V_DONE = 1 THEN
            LEAVE READ_LOOP;
        END IF;

        IF V_SALARY < 2000000 THEN
            INSERT INTO SALARY_LOG (EMP_ID, OLD_SALARY, NEW_SALARY)
            VALUES (V_EMP_ID, V_SALARY, V_SALARY);
        END IF;
    END LOOP;

    CLOSE CUR;
END $$

DELIMITER ;

CALL FLAG_LOW_SALARY();

SELECT EMP_ID, OLD_SALARY FROM SALARY_LOG ORDER BY EMP_ID;

# 5. 예외 처리 - EXIT HANDLER
DELIMITER $$

CREATE PROCEDURE GET_SALARY_SAFE(IN P_EMP_ID VARCHAR(3), OUT P_SALARY INT)
BEGIN
    DECLARE EXIT HANDLER FOR NOT FOUND
        SET P_SALARY = -1;

    SELECT SALARY INTO P_SALARY FROM EMP_COPY WHERE EMP_ID = P_EMP_ID;
END $$

DELIMITER ;

CALL GET_SALARY_SAFE('999', @sal);
SELECT @sal;

# 6. DROP PROCEDURE
DROP PROCEDURE IF EXISTS RAISE_SALARY;
DROP PROCEDURE IF EXISTS GET_DEPT_AVG_SALARY;
DROP PROCEDURE IF EXISTS CLASSIFY_SALARY;
DROP PROCEDURE IF EXISTS FLAG_LOW_SALARY;
DROP PROCEDURE IF EXISTS GET_SALARY_SAFE;

# 7. TRIGGER 기본 - AFTER UPDATE
DROP TABLE IF EXISTS EMP_COPY;
CREATE TABLE EMP_COPY AS SELECT * FROM EMP;
DELETE FROM SALARY_LOG;

DELIMITER $$

CREATE TRIGGER TRG_EMP_SALARY_LOG
AFTER UPDATE ON EMP_COPY
FOR EACH ROW
BEGIN
    IF OLD.SALARY <> NEW.SALARY THEN
        INSERT INTO SALARY_LOG (EMP_ID, OLD_SALARY, NEW_SALARY)
        VALUES (NEW.EMP_ID, OLD.SALARY, NEW.SALARY);
    END IF;
END $$

DELIMITER ;

UPDATE EMP_COPY SET SALARY = SALARY + 200000 WHERE EMP_ID = '209';

SELECT EMP_ID, OLD_SALARY, NEW_SALARY FROM SALARY_LOG WHERE EMP_ID = '209';

# 8. TRIGGER - BEFORE INSERT
DELIMITER $$

CREATE TRIGGER TRG_EMP_DEFAULT_ENTYN
BEFORE INSERT ON EMP_COPY
FOR EACH ROW
BEGIN
    IF NEW.ENT_YN IS NULL THEN
        SET NEW.ENT_YN = 'N';
    END IF;
END $$

DELIMITER ;

INSERT INTO EMP_COPY (EMP_ID, EMP_NAME, DEPT_ID, JOB_CODE, SALARY, HIRE_DATE, ENT_YN)
VALUES ('221', '테스트', 'D9', 'J7', 2000000, '2026-08-19', NULL);

SELECT EMP_ID, EMP_NAME, ENT_YN FROM EMP_COPY WHERE EMP_ID = '221';

# 9. 트리거의 무한 루프 위험 (절대 실행하지 마세요)
-- CREATE TRIGGER TRG_INFINITE
-- AFTER UPDATE ON EMP_COPY
-- FOR EACH ROW
-- BEGIN
--     UPDATE EMP_COPY SET SALARY = SALARY WHERE EMP_ID = NEW.EMP_ID;
-- END;

# 10. DROP TRIGGER
DROP TRIGGER IF EXISTS TRG_EMP_SALARY_LOG;
DROP TRIGGER IF EXISTS TRG_EMP_DEFAULT_ENTYN;
