spring.application.name=demo
# 설정파일의 주석은 #으로 작성

# 서버의 포트를 지정
# 톰켓서버의 기본포트는 8080
server.port = 7070

# 뷰템플릿에 따라 설정이 달라질수 있다
# .jsp
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html