# 1_윈도우함수.md 본문 실습 진행 스크립트 (Day 14)

# 1. 윈도우 함수란 - GROUP BY와 무엇이 다른가
SELECT EMP_NAME, DEPT_ID, SALARY,
       AVG(SALARY) OVER (PARTITION BY DEPT_ID) AS 부서평균
FROM EMP
WHERE DEPT_ID = 'D5'
ORDER BY EMP_ID;

# 2. ROW_NUMBER / RANK / DENSE_RANK
SELECT EMP_NAME, EXTRACT(YEAR FROM HIRE_DATE) AS 입사연도,
       ROW_NUMBER() OVER (ORDER BY EXTRACT(YEAR FROM HIRE_DATE) ASC) AS 순번,
       RANK()       OVER (ORDER BY EXTRACT(YEAR FROM HIRE_DATE) ASC) AS 순위,
       DENSE_RANK() OVER (ORDER BY EXTRACT(YEAR FROM HIRE_DATE) ASC) AS 밀집순위
FROM EMP
WHERE DEPT_ID = 'D9';

# 3. PARTITION BY - 그룹별로 윈도우 나누기
SELECT EMP_NAME, DEPT_ID, SALARY,
       RANK() OVER (PARTITION BY DEPT_ID ORDER BY SALARY DESC) AS 부서내순위
FROM EMP
WHERE DEPT_ID IN ('D5', 'D8')
ORDER BY DEPT_ID, 부서내순위;

# 4. LAG / LEAD - 이전/다음 행 값 참조
SELECT EMP_NAME, SALARY,
       LAG(SALARY)  OVER (ORDER BY SALARY DESC) AS 윗사람급여,
       LEAD(SALARY) OVER (ORDER BY SALARY DESC) AS 아랫사람급여
FROM EMP
WHERE DEPT_ID = 'D5'
ORDER BY SALARY DESC;

# 5. 누적 합계 - SUM() OVER
SELECT EMP_NAME, SALARY,
       SUM(SALARY) OVER (ORDER BY SALARY DESC) AS 누적합계
FROM EMP
WHERE DEPT_ID = 'D9'
ORDER BY SALARY DESC;

# 6. 그룹별 Top-N (윈도우 함수 + 인라인 뷰)
SELECT *
FROM (
    SELECT EMP_NAME, DEPT_ID, SALARY,
           RANK() OVER (PARTITION BY DEPT_ID ORDER BY SALARY DESC) AS 부서내순위
    FROM EMP
    WHERE DEPT_ID IS NOT NULL
) T
WHERE T.부서내순위 <= 2
ORDER BY DEPT_ID, 부서내순위;
