# 1_VIEW_FUNCTION.md 본문 실습 진행 스크립트 (Day 16)

# 0. 실습 준비 - 사본 테이블
DROP TABLE IF EXISTS EMP_COPY;
DROP TABLE IF EXISTS DEPT_COPY;

CREATE TABLE DEPT_COPY AS SELECT * FROM DEPT;
CREATE TABLE EMP_COPY  AS SELECT * FROM EMP;

# 1. VIEW란 - 저장된 SELECT문
CREATE VIEW V_D9_EMP AS
SELECT EMP_ID, EMP_NAME, SALARY, HIRE_DATE
FROM EMP_COPY
WHERE DEPT_ID = 'D9';

SELECT * FROM V_D9_EMP ORDER BY EMP_ID;

# 2. 복합 뷰 (JOIN + 집계 포함)
CREATE VIEW V_DEPT_AVG_SALARY AS
SELECT D.DEPT_ID, D.DEPT_TITLE, ROUND(AVG(E.SALARY)) AS 평균급여, COUNT(*) AS 인원수
FROM EMP_COPY E
JOIN DEPT_COPY D ON E.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_ID, D.DEPT_TITLE;

SELECT * FROM V_DEPT_AVG_SALARY ORDER BY 평균급여 DESC;

# 3. 뷰를 통한 UPDATE - 갱신 가능한 뷰
CREATE VIEW V_D8_EMP AS
SELECT EMP_ID, EMP_NAME, DEPT_ID, SALARY
FROM EMP_COPY
WHERE DEPT_ID = 'D8';

UPDATE V_D8_EMP SET SALARY = SALARY + 100000 WHERE EMP_ID = '210';

SELECT EMP_ID, EMP_NAME, SALARY FROM EMP_COPY WHERE EMP_ID = '210';

# 4. WITH CHECK OPTION
DROP VIEW IF EXISTS V_D8_EMP;

CREATE VIEW V_D8_EMP AS
SELECT EMP_ID, EMP_NAME, DEPT_ID, SALARY
FROM EMP_COPY
WHERE DEPT_ID = 'D8'
WITH CHECK OPTION;

-- 아래 UPDATE는 CHECK OPTION 위반으로 오류가 납니다.
UPDATE V_D8_EMP SET DEPT_ID = 'D1' WHERE EMP_ID = '210';

# 6. DROP VIEW
DROP VIEW IF EXISTS V_D9_EMP;
DROP VIEW IF EXISTS V_DEPT_AVG_SALARY;
DROP VIEW IF EXISTS V_D8_EMP;

# 7.2 사용자정의 FUNCTION - 예제 1 (한 줄 함수)
DELIMITER $$

CREATE FUNCTION GET_ANNUAL_SALARY(P_SALARY INT, P_BONUS DECIMAL(4,2))
RETURNS INT
DETERMINISTIC
BEGIN
    RETURN (P_SALARY + P_SALARY * IFNULL(P_BONUS, 0)) * 12;
END $$

DELIMITER ;

SELECT EMP_NAME, SALARY, BONUS, GET_ANNUAL_SALARY(SALARY, BONUS) AS 연봉
FROM EMP_COPY
WHERE DEPT_ID = 'D5'
ORDER BY 연봉 DESC;

# 7.3 예제 2 (DECLARE + IF + RETURN)
DELIMITER $$

CREATE FUNCTION SALARY_GRADE(P_SALARY INT)
RETURNS VARCHAR(10)
DETERMINISTIC
BEGIN
    DECLARE V_GRADE VARCHAR(10);

    IF P_SALARY >= 6000000 THEN
        SET V_GRADE = 'A';
    ELSEIF P_SALARY >= 4000000 THEN
        SET V_GRADE = 'B';
    ELSEIF P_SALARY >= 2500000 THEN
        SET V_GRADE = 'C';
    ELSE
        SET V_GRADE = 'D';
    END IF;

    RETURN V_GRADE;
END $$

DELIMITER ;

SELECT EMP_NAME, SALARY, SALARY_GRADE(SALARY) AS 급여등급
FROM EMP_COPY
ORDER BY SALARY DESC;

# 8. DROP FUNCTION
DROP FUNCTION IF EXISTS GET_ANNUAL_SALARY;
DROP FUNCTION IF EXISTS SALARY_GRADE;
