DROP TABLE IF EXISTS EMP;
DROP TABLE IF EXISTS DEPT;
DROP TABLE IF EXISTS JOB;

CREATE TABLE DEPT (
    DEPT_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    DEPT_NAME VARCHAR(50)  NOT NULL,
    LOCATION  VARCHAR(50)
);

CREATE TABLE JOB (
    JOB_CODE VARCHAR(10) PRIMARY KEY,
    JOB_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE EMP (
    EMP_ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMP_NAME   VARCHAR(50)  NOT NULL,
    EMAIL      VARCHAR(100) NOT NULL UNIQUE,
    PHONE      VARCHAR(20),
    DEPT_ID    BIGINT,
    JOB_CODE   VARCHAR(10),
    SALARY     INT NOT NULL DEFAULT 0,
    MANAGER_ID BIGINT,
    HIRE_DATE  DATE NOT NULL,
    ACTIVE     TINYINT(1) NOT NULL DEFAULT 1,
    MEMO       VARCHAR(200),
    CONSTRAINT FK_EMP_DEPT    FOREIGN KEY (DEPT_ID)    REFERENCES DEPT (DEPT_ID),
    CONSTRAINT FK_EMP_JOB     FOREIGN KEY (JOB_CODE)   REFERENCES JOB (JOB_CODE),
    CONSTRAINT FK_EMP_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES EMP (EMP_ID)
);
